import { Colors } from "@/constants/theme";
import { StyleSheet } from "react-native";

export type Scheme = "light" | "dark" | null;

export const getSearchStyles = (colorScheme: Scheme) =>
  StyleSheet.create({
    container: {
      flex: 1,
    },
    contentContainer: {
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 40,
    },
    headerSection: {
      marginBottom: 24,
    },
    headerTitle: {
      fontSize: 34,
      fontWeight: "800",
      letterSpacing: -0.5,
      marginBottom: 6,
    },
    headerSubtitle: {
      fontSize: 14,
      color: Colors[colorScheme ?? "light"].muted,
      marginTop: 4,
    },
    toggleContainer: {
      flexDirection: "row",
      gap: 10,
      marginBottom: 20,
    },
    toggleButton: {
      flex: 1,
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: Colors[colorScheme ?? "light"].border,
    },
    toggleButtonActive: {},
    toggleText: {
      fontWeight: "600",
      fontSize: 14,
    },
    toggleTextActive: {
      color: "white",
    },
    card: {
      marginBottom: 20,
      paddingHorizontal: 16,
      paddingVertical: 16,
      borderRadius: 16,
      backgroundColor: Colors[colorScheme ?? "light"].surface,
      borderWidth: 0,
      // Modern soft shadow
      shadowColor: "#000000",
      shadowOpacity: 0.08,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
      elevation: 3,
    },
    cardTitle: {
      marginBottom: 14,
      fontWeight: "600",
    },
    input: {
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: Colors[colorScheme ?? "light"].border,
      fontSize: 15,
      marginBottom: 12,
      color: Colors[colorScheme ?? "light"].text,
      backgroundColor: Colors[colorScheme ?? "light"].surface,
    },
    searchButton: {
      flexDirection: "row",
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      shadowColor: "#000000",
      shadowOpacity: 0.08,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 5 },
      elevation: 2,
    },
    searchButtonIcon: {
      fontSize: 18,
    },
    searchButtonText: {
      color: "white",
      fontWeight: "700",
      fontSize: 14,
    },
    imagePickerButtons: {
      flexDirection: "row",
      gap: 10,
    },
    imageButton: {
      flex: 1,
      paddingVertical: 14,
      paddingHorizontal: 12,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
    },
    imageButtonIcon: {
      fontSize: 24,
    },
    imageButtonText: {
      color: "white",
      fontWeight: "600",
      fontSize: 12,
    },
    imageSelectedContainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      backgroundColor: Colors[colorScheme ?? "light"].surface,
      padding: 10,
      borderRadius: 10,
      marginBottom: 12,
    },
    selectedImage: {
      width: 70,
      height: 70,
      borderRadius: 8,
    },
    imageInfo: {
      flex: 1,
    },
    imageName: {
      fontWeight: "600",
      fontSize: 13,
      marginBottom: 2,
    },
    imageDimensions: {
      fontSize: 12,
      color: Colors[colorScheme ?? "light"].muted,
    },
    clearImageButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: Colors[colorScheme ?? "light"].danger,
      alignItems: "center",
      justifyContent: "center",
    },
    errorAlert: {
      marginBottom: 16,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: 10,
      backgroundColor: Colors[colorScheme ?? "light"].surface,
      borderLeftWidth: 4,
      borderLeftColor: Colors[colorScheme ?? "light"].danger,
    },
    errorText: {
      color: Colors[colorScheme ?? "light"].danger,
      fontWeight: "500",
      fontSize: 14,
    },
    resultsSection: {
      marginBottom: 20,
    },
    resultHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 14,
    },
    resultCount: {
      backgroundColor: Colors[colorScheme ?? "light"].surface,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 20,
    },
    resultCountText: {
      fontSize: 12,
      fontWeight: "600",
    },
    resultCard: {
      flexDirection: "row",
      borderRadius: 12,
      overflow: "hidden",
      marginVertical: 8,
      backgroundColor: Colors[colorScheme ?? "light"].surface,
      borderWidth: 0,
      shadowColor: "#000000",
      shadowOpacity: 0.06,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
    },
    resultImage: {
      width: 100,
      height: 100,
    },
    resultContent: {
      flex: 1,
      padding: 12,
      justifyContent: "center",
    },
    resultName: {
      fontWeight: "700",
      marginBottom: 2,
    },
    breedText: {
      fontSize: 13,
      color: Colors[colorScheme ?? "light"].muted,
      marginBottom: 8,
    },
    confidenceContainer: {
      gap: 4,
    },
    confidenceBar: {
      height: 6,
      backgroundColor: Colors[colorScheme ?? "light"].tint,
      borderRadius: 3,
    },
    confidenceText: {
      fontSize: 11,
      color: Colors[colorScheme ?? "light"].muted,
      fontWeight: "500",
    },
    separator: {
      height: 0,
    },
    emptyState: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 60,
    },
    emptyStateIcon: {
      fontSize: 64,
      lineHeight: 72,
      marginBottom: 16,
    },
    emptyStateTitle: {
      fontSize: 18,
      fontWeight: "700",
      marginBottom: 8,
    },
    emptyStateText: {
      fontSize: 14,
      color: Colors[colorScheme ?? "light"].muted,
      textAlign: "center",
      paddingHorizontal: 20,
    },
  });

export const getUploadStyles = (colorScheme: Scheme) =>
  StyleSheet.create({
    container: {
      flex: 1,
    },
    contentContainer: {
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 40,
    },
    headerSection: {
      marginBottom: 24,
    },
    headerTitle: {
      fontSize: 34,
      fontWeight: "800",
      letterSpacing: -0.5,
      marginBottom: 6,
    },
    headerSubtitle: {
      fontSize: 14,
      color: Colors[colorScheme ?? "light"].muted,
      marginTop: 4,
    },
    card: {
      marginBottom: 20,
      paddingHorizontal: 16,
      paddingVertical: 16,
      borderRadius: 16,
      backgroundColor: Colors[colorScheme ?? "light"].surface,
      borderWidth: 0,
      shadowColor: "#000000",
      shadowOpacity: 0.08,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
      elevation: 3,
    },
    sectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 12,
    },
    cardTitle: {
      marginBottom: 16,
      fontWeight: "600",
      fontSize: 18,
    },
    cardTitleRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
    },
    multiModeCheckbox: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    checkbox: {
      width: 24,
      height: 24,
      borderRadius: 6,
      borderWidth: 2,
      borderColor: Colors[colorScheme ?? "light"].border,
      backgroundColor: Colors[colorScheme ?? "light"].surface,
      alignItems: "center",
      justifyContent: "center",
    },
    checkboxChecked: {
      backgroundColor: Colors[colorScheme ?? "light"].tint,
      borderColor: Colors[colorScheme ?? "light"].tint,
    },
    checkmark: {
      color: "white",
      fontSize: 16,
      fontWeight: "700",
    },
    checkboxLabel: {
      fontSize: 14,
      fontWeight: "500",
      color: Colors[colorScheme ?? "light"].text,
    },
    uploadContainer: {
      borderWidth: 2,
      borderStyle: "dashed",
      borderColor: Colors[colorScheme ?? "light"].border,
      borderRadius: 16,
      paddingVertical: 40,
      paddingHorizontal: 24,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: Colors[colorScheme ?? "light"].background,
      position: "relative",
    },
    uploadIcon: {
      fontSize: 48,
      lineHeight: 56,
      marginBottom: 16,
    },
    uploadTitle: {
      fontSize: 16,
      fontWeight: "600",
      marginBottom: 8,
    },
    uploadSubtitle: {
      fontSize: 13,
      color: Colors[colorScheme ?? "light"].muted,
      marginBottom: 20,
    },
    cameraIconButton: {
      position: "absolute",
      top: 16,
      right: 16,
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: "#FFF3E0",
      alignItems: "center",
      justifyContent: "center",
    },
    cameraIcon: {
      fontSize: 24,
      lineHeight: 28,
    },
    galleryButton: {
      flexDirection: "row",
      paddingVertical: 14,
      paddingHorizontal: 24,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      backgroundColor: Colors[colorScheme ?? "light"].tint,
      shadowColor: "#000000",
      shadowOpacity: 0.1,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
    },
    galleryButtonIcon: {
      fontSize: 20,
    },
    galleryButtonText: {
      color: "white",
      fontWeight: "600",
      fontSize: 15,
    },
    photoButtonsGroup: {
      flexDirection: "row",
      gap: 12,
    },
    photoButton: {
      flex: 1,
      paddingVertical: 16,
      paddingHorizontal: 12,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    photoButtonIcon: {
      fontSize: 28,
      marginBottom: 6,
    },
    photoButtonText: {
      color: "white",
      fontWeight: "600",
      fontSize: 13,
    },
    imagePreviewSection: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      backgroundColor: Colors[colorScheme ?? "light"].surface,
      padding: 12,
      borderRadius: 12,
    },
    imagePreview: {
      width: 80,
      height: 80,
      borderRadius: 12,
    },
    imageDetails: {
      flex: 1,
    },
    imageName: {
      fontWeight: "600",
      fontSize: 13,
      marginBottom: 2,
    },
    imageDimensions: {
      fontSize: 12,
      color: Colors[colorScheme ?? "light"].muted,
    },
    removeButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: Colors[colorScheme ?? "light"].danger,
      alignItems: "center",
      justifyContent: "center",
    },
    formGroup: {
      marginBottom: 16,
    },
    labelContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 8,
      gap: 6,
    },
    labelIcon: {
      fontSize: 16,
    },
    label: {
      fontSize: 15,
      fontWeight: "600",
    },
    required: {
      color: "#ff4444",
      marginLeft: 4,
      fontWeight: "700",
    },
    optional: {
      color: Colors[colorScheme ?? "light"].muted,
      fontSize: 12,
      marginLeft: 4,
      fontWeight: "500",
    },
    input: {
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: Colors[colorScheme ?? "light"].border,
      fontSize: 15,
      color: Colors[colorScheme ?? "light"].text,
      backgroundColor: Colors[colorScheme ?? "light"].surface,
    },
    textArea: {
      minHeight: 100,
      paddingTop: 12,
      paddingBottom: 12,
    },
    characterCounter: {
      fontSize: 12,
      color: Colors[colorScheme ?? "light"].muted,
      textAlign: "right",
      marginTop: 6,
    },
    pickerContainer: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: Colors[colorScheme ?? "light"].border,
      backgroundColor: Colors[colorScheme ?? "light"].surface,
    },
    pickerText: {
      fontSize: 15,
      color: Colors[colorScheme ?? "light"].text,
      flex: 1,
    },
    pickerPlaceholder: {
      color: Colors[colorScheme ?? "light"].muted,
    },
    pickerIcon: {
      fontSize: 14,
      color: Colors[colorScheme ?? "light"].muted,
    },
    errorAlert: {
      marginBottom: 16,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: 10,
      backgroundColor: Colors[colorScheme ?? "light"].surface,
      borderLeftWidth: 4,
      borderLeftColor: Colors[colorScheme ?? "light"].danger,
    },
    errorText: {
      color: Colors[colorScheme ?? "light"].danger,
      fontWeight: "500",
      fontSize: 14,
    },
    successAlert: {
      marginBottom: 16,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: 10,
      backgroundColor: Colors[colorScheme ?? "light"].surface,
      borderLeftWidth: 4,
      borderLeftColor: Colors[colorScheme ?? "light"].success,
    },
    successText: {
      color: Colors[colorScheme ?? "light"].success,
      fontWeight: "500",
      fontSize: 14,
    },
    buttonGroup: {
      gap: 10,
      marginBottom: 12,
    },
    uploadButton: {
      flexDirection: "row",
      paddingVertical: 18,
      paddingHorizontal: 16,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      shadowColor: "#000000",
      shadowOpacity: 0.12,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 5 },
      elevation: 3,
    },
    uploadButtonIcon: {
      fontSize: 20,
    },
    uploadButtonText: {
      color: "white",
      fontWeight: "700",
      fontSize: 16,
    },
    clearButton: {
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: Colors[colorScheme ?? "light"].surface,
      borderWidth: 1.5,
      borderColor: Colors[colorScheme ?? "light"].border,
    },
    clearButtonText: {
      fontWeight: "600",
      fontSize: 14,
    },
    requiredNote: {
      paddingHorizontal: 0,
      paddingVertical: 8,
    },
    requiredNoteText: {
      fontSize: 12,
      color: Colors[colorScheme ?? "light"].muted,
      textAlign: "center",
    },
    // Mode toggle styles
    modeToggleContainer: {
      flexDirection: "row",
      gap: 10,
      marginBottom: 8,
    },
    modeButton: {
      flex: 1,
      paddingVertical: 12,
      paddingHorizontal: 12,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1.5,
      borderColor: Colors[colorScheme ?? "light"].border,
      backgroundColor: Colors[colorScheme ?? "light"].surface,
    },
    modeButtonActive: {
      backgroundColor: Colors[colorScheme ?? "light"].tint,
      borderColor: Colors[colorScheme ?? "light"].tint,
    },
    modeButtonText: {
      fontWeight: "600",
      fontSize: 13,
      color: Colors[colorScheme ?? "light"].text,
    },
    modeButtonTextActive: {
      color: "white",
    },
    // Multiple images styles
    imageCountText: {
      fontSize: 14,
      fontWeight: "600",
      marginBottom: 12,
      color: Colors[colorScheme ?? "light"].text,
    },
    multiImageScroll: {
      flexDirection: "row",
    },
    multiImageItemContainer: {
      position: "relative",
      marginRight: 12,
      marginBottom: 8,
    },
    multiImagePreview: {
      width: 100,
      height: 100,
      borderRadius: 10,
      backgroundColor: Colors[colorScheme ?? "light"].border,
    },
    removeButtonSmall: {
      position: "absolute",
      top: -6,
      right: -6,
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: Colors[colorScheme ?? "light"].danger,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: Colors[colorScheme ?? "light"].surface,
    },
    addMoreButton: {
      width: 100,
      height: 100,
      borderRadius: 10,
      borderWidth: 2,
      borderStyle: "dashed",
      borderColor: Colors[colorScheme ?? "light"].border,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: Colors[colorScheme ?? "light"].background,
    },
    addMoreButtonText: {
      fontSize: 13,
      fontWeight: "600",
      color: Colors[colorScheme ?? "light"].tint,
      textAlign: "center",
    },
  });
